config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/index'
  resources :carts
  resources :menu_items
  devise_for :users
  resources :restaurants do
    resources :comments
  end
  delete "cart_item/:id", to: "carts#cart_item_delete", as: "cart_item_delete"
  post "order/:id", to: "carts#order", as: "order"
  get "reorder/:id", to: "carts#reorder", as: "reorder"
  # delete "url", to: "controller#action_name", as: "path_name"
  root "restaurants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_one :my_order, dependent: :destroy
  def items
    cart_items.count
  end


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item
  belongs_to :user

  def restrau_name
    menu_item.restaurant.name
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant
  has_many :cart_items
end

app/models/my_order.rb
class MyOrder < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  belongs_to :cart
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :menu_items
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :carts
  has_many :cart_items
  has_many :my_orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :get_menu_item, only: [:update]
  before_action :ordered_cart, only: [:index, :update]
  def index
    unless current_user.carts.present? and !@ordered_cart.include?(current_user.carts.last.id)
      cart=current_user.carts.build
      cart.save
    end 
    @cart=current_user.carts.last
  end

  def update
    @restaurant=Restaurant.find(params[:restaurant_id])
    unless current_user.carts.present? and !@ordered_cart.include?(current_user.carts.last.id)
      @cart = Cart.create(user_id: current_user.id)
    else
      @cart=current_user.carts.last
    end
    @cart.total+=@menu_item.price
    @cart.save
    cart_item = CartItem.create(user_id: current_user.id, menu_item_id: @menu_item.id, cart_id: @cart.id) 
    flash[:notice]= "Item Added"
    redirect_to @restaurant
  end

  def cart_item_delete
    @cart_item= CartItem.find(params[:id])
    @cart = @cart_item.cart
    @cart.total -= @cart_item.menu_item.price
    @cart.save
    if @cart_item.destroy
      redirect_to carts_path
      flash[:notice]= "Successfully Remove item"
    else
    flash[:error]= "Not Remove item"
    end
  end

  def order
    @cart=Cart.find(params[:id])
    @my_order=MyOrder.new(user_id: current_user.id, cart_id: @cart.id, total: @cart.total, ordered_at: Date.today)
    @my_order.save
    cart = current_user.carts.build
    cart.save
    flash[:notice]= "Order Placed"
    redirect_to root_path
  end

  def reorder
    current_user.carts.last.destroy
    @cart=Cart.find(params[:id])
    @reorder=current_user.carts.build
    @reorder.total=@cart.total
    @reorder.save
    @cart.cart_items.each do |item|
      
      cart_item = CartItem.create(user_id: current_user.id, menu_item_id: item.menu_item.id, cart_id: @reorder.id) 
    end
    redirect_to carts_path
  end

  private

  def get_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def ordered_cart
    @ordered_cart= MyOrder.pluck(:cart_id)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_restaurant
  before_action :find_comment, only: [:show, :edit,:update, :destroy]

  def create
    @comment= @restaurant.comments.build(comment_params)
    @comment.user_id= current_user.id
    if @comment.save
        flash[:notice]= "Successfully Created Comment"
        redirect_to restaurant_path(@restaurant)
    end
    
  end

  def edit
     
    
  end

  def update
      if @comment.update(comment_params)
        flash[:notice]= "Successfully Updated Comment"
        redirect_to restaurant_path(@restaurant)
      else
        flash[:error]= "Comment not Updated"
        render 'edit'
      end
  end

  def destroy
      if @comment.destroy
          redirect_to restaurant_path(@restaurant)
          flash[:notice]= "Successfully Deleted Comment"
      else
      flash[:error]= "Comment not deleted"
      end
  end



  private

  def comment_params
      params.require(:comment).permit(:content)
  end

  def find_restaurant
      @restaurant=Restaurant.find(params[:restaurant_id])
  end

  
  def find_comment
      @comment = @restaurant.comments.find(params[:id])
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @menu_item=MenuItem.new
  end

  def create
    @restaurant=Restaurant.find(params[:restaurant_id])
    @menu_item=@restaurant.menu_items.build(menu_item_params)
    if @menu_item.save
      flash[:notice] = "Successfully menu created"
      redirect_to restaurant_path(@restaurant)          
    else
        render 'new'
    end
  end

  def edit
  end

  private
  
  def menu_item_params
    params.require(:menu_item).permit(:name, :price)
  end

end

app/controllers/my_orders_controller.rb
class MyOrdersController < ApplicationController
  def index
    @my_orders=current_user.my_orders.order(created_at: :desc)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]
  def index
    @restaurants= Restaurant.all
  end

  def show 
  end

  private

  def find_restaurant
    @restaurant=Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/my_orders_helper.rb
module MyOrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/carts/index.html.erb
<div class="container">
    <h2>Your Items</h2>
    <table class="table table-striped table-hover" style="background-color:#b2ebf2 ">
    <thead class="table-primary">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @cart.cart_items.each_with_index do |item,i|%>
            <tr>
                <td scope="row"><%=i+1%></td>
                <td><%=item.menu_item.name%></td>
                <td><%=item.menu_item.price%></td>
                <td><%=link_to cart_item_delete_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this item"} do %>
                    <i class="fa fa-times text-danger"></i>
                <%end%>
            </tr>
        <%end%>
         <tr class="table-danger">
            <td scope="row"></td>
            <td>Total</td>
            <td><%=@cart.total%></td>
            <td></td>
        </tr>
    </tbody>
    </table>
    <%unless @cart.total==0%>
        <div class="d-grid gap-2 d-md-block col-3 mx-auto btn-lg">
            <%=link_to "Order Now", order_path(@cart),data: {turbo_method: :post}, class:"btn btn-success"%>
        </div>
    <%end%>
</div>

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<div class="d-flex justify-content-between">
<p>Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
<% if user_signed_in? %>
    <% if comment.user_id== current_user.id%>
        <div>
            <%=link_to edit_restaurant_comment_path(comment.restaurant,comment), class: "btn btn-light" do %>
                <i class="fa fa-pencil-square-o"></i>
            <%end%>
            <%=link_to restaurant_comment_path(comment.restaurant,comment), data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this comment"}, class: "btn btn-danger" do %>
                <i class="fa fa-trash"></i>
            <%end%>
        </div>
    <%end%>
<%end%>
</div>
<hr>
   

app/views/comments/_form.html.erb
<div class="container">
    <%= form_with model: comment, url: url do |form|%>
    <div class="mb-3">
        <%=form.label :content, class:"form-label"%>
        <%=form.text_area :content, class:'form-control'%>
    </div>
    <div class="mb-3">
        <%=form.submit class: "btn btn-primary"%>
        <%=link_to "Back", :back, class: "btn btn-warning"%>
    </div>
    <%end%>
</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render "form", comment: @comment, url: restaurant_comment_path(@restaurant)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hungerpoint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>

  <body style="background-image: url('https://t3.ftcdn.net/jpg/03/51/57/44/360_F_351574443_6mZtd2RFcaGXJQPABkbMEV76lRwltn0q.jpg');">
    <%=render "shared/header"%>
    <%#=render "shared/success"%>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/menu_items/_form.html.erb
<div class="container">
    <%=form_with model: menu_item, url: url do |form|%>
        <div class="mb-3">
            <%=form.label :name, class:'form-label'%><br>
            <%=form.text_field :name, class:"form-control"%>
        </div>
        <div class="mb-3">
            <%=form.label :price, class:'form-label'%><br>
            <%=form.text_area :price, class:"form-control"%>
        </div>

        <br>
        <div class="mb-3 text-center">
            <%=form.submit class:"btn btn-primary"%>
            <%=link_to "Back", :back, class: "btn btn-warning"%>
        </div>
    <%end%>
<div>

app/views/menu_items/edit.html.erb
<h1>MenuItems#edit</h1>
<p>Find me in app/views/menu_items/edit.html.erb</p>

app/views/menu_items/index.html.erb
<h1>MenuItems#index</h1>
<p>Find me in app/views/menu_items/index.html.erb</p>

app/views/menu_items/new.html.erb
<br>
<h1 class="text-center">ADD MENU</h1>
<%=render "form", menu_item: @menu_item, url: menu_items_path(restaurant_id: params[:restaurant_id]) %>

app/views/menu_items/show.html.erb
<h1>MenuItems#show</h1>
<p>Find me in app/views/menu_items/show.html.erb</p>

app/views/my_orders/index.html.erb
<div class="container">
    <h1 class="text-center">MyOrders</h1>
    <div class="card bg-transparent" >
        <%@my_orders.each do |order|%>
            <div class="card mb-3" style="background-color: #e9eca7;">
                <% items=order.cart.cart_items %>
                <div class="card-title d-flex justify-content-between mx-2">
                    <h1 class="display-4">Order No.<%=order.cart.id%></h1>
                    <p>Ordered At: <%=order.ordered_at.strftime("%d-%m-%Y")%></p>
                </div>
                <h3 class="card-subtitle mb-2 text-muted mx-2"><%= items.first.restrau_name %></h3>
                <div class="card-body">
                    <%items.each do |item|%>
                        <div class="d-flex justify-content-between">
                            <p class="lead"><%=item.menu_item.name%></p>
                            <p class="text-muted"><%=item.menu_item.price%></p>
                        </div>
                        <hr class="my-4">
                    <%end%>
                    <div class="d-flex justify-content-between mb-3">
                        <p class="lead">Grand Total:</p>
                        <p><%=order.total%></p>
                    </div>
                    <div class="d-flex justify-content-end mb-3">
                        <%= link_to 'Reorder', reorder_path(order.cart), class:"btn btn-primary"%>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/restaurants/index.html.erb
<h1 class="text-center">Restaurants</h1>
<div class="row">
<%@restaurants.each do |restaurant|%>
    <%=link_to restaurant_path(restaurant), class: "mt-5 col-4 mx-3 text-decoration-none text-dark",style:"width: 21rem;" do%>
        <div class="card  border-3" style="width: 21rem;border-bottom-color:#80ff52; background-color:#ffb999;min-height:600px;">
            <h5 class="card-title text-dark gw-bold mx-3 mt-2"><%=restaurant.name%></h5>
            <div class="card-body ">
                <p class="card-text">Food type: <%=restaurant.menu%></p>
                <p class="card-text">Location: <%=restaurant.location%></p>
                <hr>
                <div class="fa-stack">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <i class="fa fa-star fa-stack-1x"></i>
                </div>
                <h6 class="card-subtitle mb-2 text-muted" style="display:inline"><%= restaurant.review%></h6>
                <br>
                <br>
            </div>
        </div>
    <%end%>
<%end%>
</div>

app/views/restaurants/show.html.erb
<h1 class="text-center"><%=@restaurant.name%></h1>
<h4 class="text-center"><%=@restaurant.location%></h4>
<hr>
<%=link_to "ADD MENU", new_menu_item_path(restaurant_id: @restaurant), class:"btn btn-primary mb-4 mt-4"%>

<div class="container">
    <h2>Menu-Items</h2>
    <table class="table table-danger table-striped table-hover">
    <thead class="table-primary">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @restaurant.menu_items.each_with_index do |menu,i|%>
            <tr>
                <td scope="row"><%=i+1%></td>
                <td><%=menu.name%></td>
                <td><%=menu.price%></td>
                <td><%=link_to "ADD TO CART",cart_path(menu,restaurant_id:  @restaurant),data:{turbo_method: :put} ,class:"btn btn-outline-primary"%></td>
            </tr>
        <%end%>
    </tbody>
    </table>

    <br>
    <div style="background-color:#ffebee">
        <div class="mx-3">
        <h3>Reviews:</h3>
        <%=render @restaurant.comments%>
        <h3>Share Your Views:</h3>
        <%= render 'comments/form', comment:  @restaurant.comments.build, url: restaurant_comments_path(@restaurant)%>
        </div>
        
        
    </div>

</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-danger sticky-top d-flex justify-content-between">
  <div class="mt-1 navbar-brand">
    <div class="card mx-3">
      <%= link_to root_path do %>
        <%= image_tag "https://www.hungerspoint.online/uploads/96ae86787293146d1a29f861ed9ecab3.png",width:"194px", height:"49px" %>
      <% end %>
    </div>
  </div>
    <div class="navbar-nav">
        <%=render "shared/success"%>
    </div>
  <div>
      <%# <a class="navbar-brand" href="">Hunger Point</a> %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse mx-3" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%=link_to '<i class="fa fa-shopping-bag fa-2x mt-2 text-info"></i>'.html_safe, my_orders_index_path,class: "nav-link",data: {title: "My order"} %>
            </li>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-sign-out fa-2x mt-2 text-secondary"></i>'.html_safe, destroy_user_session_path, data: {turbo_method: :delete, title: "Sign Out"},class: "nav-link"%>
            </li>
          <%else%>
            <li class="nav-item">
              <%=link_to  '<i class="fa fa-user-plus fa-2x mt-2 text-warning"></i>'.html_safe, new_user_registration_path,class: "nav-link",data: {title: "Sign up"}  %>
            </li>
            <li class="nav-item">
              <%= link_to '<i class="fa fa-sign-in fa-2x mt-2 text-primary"></i>'.html_safe, new_user_session_path, class: "nav-link",data: {title: "Sign in"}, style: "margin-right:30px;"%>
            </li>
          <%end%>
        </ul>
        <%# <form class="d-flex mx-3">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> %>

        <% if user_signed_in? %>
        <div class="rounded-circle bg-light text-center" style="height:46px;width:70px; margin-right:30px;">
          <%=link_to carts_path ,data: {title: "My Cart"} do %>
            <i class="fa fa-shopping-cart fa-2x mx-3 text-primary mt-2" aria-hidden="true">
              <span class="position-absolute top-5 start-99 translate-middle badge rounded-pill text-dark mt-2" style="font-size:15px;margin-left:8px;">
              <% if current_user.carts.present?%>
                <%= current_user.carts.last.items %>
              <%else%>
                0
              <%end%>
              <span class="visually-hidden">Items</span>
            </span>
            </i>
          <%end%>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_success.html.erb
<div class="messages">
  <%flash.each do |name,msg|%>
    <div class="alert alert-success alert-dismissible fade show" style="max-height:50px;" role="alert">
      <p id="alert-content"><%=msg%></p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <%end%>
</div>